[package]
name = "debug-graph"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
geo = "0.27.0"
geojson = { git = "https://github.com/georust/geojson" }
route-snapper-graph = { path = "../route-snapper-graph" }
serde_json = "1.0.107"
