[package]
name = "osm-to-route-snapper"
version = "0.1.0"
edition = "2021"

[dependencies]
abstutil = { git = "https://github.com/a-b-street/abstreet" }
bincode = "1.3.1"
clap = { version = "4.0.32", features = ["derive"] }
geom = { git = "https://github.com/a-b-street/abstreet" }
osm2streets = { git = "https://github.com/a-b-street/osm2streets" }
route-snapper-graph = { path = "../route-snapper-graph" }
streets_reader = { git = "https://github.com/a-b-street/osm2streets" }
