[package]
name = "route-snapper-graph"
version = "0.1.0"
edition = "2021"

[dependencies]
geo = { version = "0.27.0", features = ["use-serde"] }
serde = { version = "1.0.188", features = ["derive"] }
